### ISSUE TITLE
Change MD Config to specify sim duration not number of steps

### ISSUE THREAD

**Issue by M-R-Schaefer** [apax-hub/apax#53]
To better conform to other MD codes we should implement a config roughly like the following.

```yaml
duration: 10_000 # fs
sampling_interval: 100 # fs
timestep: 0.5 # fs
```

Thanks to @PythonFZ for bringing this up.
