### ISSUE TITLE
Disbale loss

### ISSUE THREAD

**Issue by PythonFZ** [apax-hub/apax#80]
It would be nice, if one could disable a certain loss by setting its weight to zero / null

```yaml
loss:
- name: energy
  loss_type: structures
- name: forces
  loss_type: structures
  weight: 0.0 # this
- name: forces
  loss_type: angles
  weight: null # or this
```
